### ISSUE TITLE
連絡所

### ISSUE THREAD

**Issue by yuzame** [furoagari/HelloHack#1]
![fd5665c2](https://cloud.githubusercontent.com/assets/11313782/6539868/852ccdec-c4c5-11e4-8e09-d22eb41066b5.jpg)

**Comment by yuzame** [comment]
http://www.ooedoonsen.jp/daiba/price.html
土日・祝日：2,680円
六本木→テレコムセンター
12:52発→13:25着(33分)

六本木→東京テレポート
13:00発→13:29着（29分）

**Comment by yuzame** [comment]
http://192.168.154.12

**Comment by yuzame** [comment]
http://cylonjs.com/documentation/platforms/edison/

**Comment by yuzame** [comment]
angle
relay
serbo

**Comment by cloverrose** [comment]
```
wget  http://python-distribute.org/distribute_setup.py
python distribute_setup.py

wget  http://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
```

---

これ古いやり方だった
 easy_install pipでできた

**Comment by yuzame** [comment]
http://d.hatena.ne.jp/tarao/20111212/1323660106

<VirtualHost *:80>
    ServerName xdr.example.org

```
ProxyPassMatch ^/http://(.*)$ http://$1
<Proxy *>
    Allow from all
</Proxy>

Header add Access-Control-Allow-Origin "*"
```

</VirtualHost>

**Comment by yuzame** [comment]
Header add Access-Control-Allow-Origin "*"

**Comment by cloverrose** [comment]
http://210.140.162.51/static/graph.html
